apiVersion: 1

datasources:
  - name: PostgreSQL Warehouse
    type: grafana-postgresql-datasource
    access: proxy
    url: postgres:5432
    database: unilever_warehouse
    user: postgres
    secureJsonData:
      password: "123456"
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 140
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      
  - name: Prometheus
    type: prometheus
    access: proxy
    url: prometheus:9090
    isDefault: false
    editable: true
