name: Test and Deploy ETL Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest pytest-cov
    
    - name: Setup database
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: postgres
      run: |
        psql -c "CREATE DATABASE unilever_warehouse;"
        psql unilever_warehouse -f 01-warehouse-design/schema/star_schema.sql
    
    - name: Run tests
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: postgres
        PGDATABASE: unilever_warehouse
      run: |
        pytest tests/ -v --cov=04-etl-pipeline --cov-report=xml
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        fail_ci_if_error: false
        verbose: true
    
    - name: Run linting
      run: |
        pip install flake8 black
        black --check 04-etl-pipeline/ 05-airflow-orchestration/
        flake8 04-etl-pipeline/ 05-airflow-orchestration/ --max-line-length=100

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -f 09-deployment/docker/Dockerfile.etl -t unilever/etl-pipeline:latest -t unilever/etl-pipeline:${{ github.sha }} .
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image
      run: |
        docker push unilever/etl-pipeline:latest
        docker push unilever/etl-pipeline:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to AWS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1
      run: |
        chmod +x 09-deployment/cloud-deploy/aws-deploy.sh
        bash 09-deployment/cloud-deploy/aws-deploy.sh update
    
    - name: Notify Teams
      uses: jdcargile/ms-teams-notification@v1.3
      with:
        github-token: ${{ github.token }}
        ms-teams-webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
        notification-color: 3399ff
        title: Unilever ETL Pipeline Deployed
        description: Version ${{ github.sha }} deployed to production
        
    - name: Smoke tests
      run: |
        sleep 30
        curl -f http://${{ secrets.PROD_SERVER_IP }}:8000/health || exit 1
